// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV50NxjjGVZZjDmBFBLncbqxPpZ60kgO0',
    appId: '1:400583872344:web:d1ec48146bdd4b5dd39f2d',
    messagingSenderId: '400583872344',
    projectId: 'chat-app-a3183',
    authDomain: 'chat-app-a3183.firebaseapp.com',
    storageBucket: 'chat-app-a3183.appspot.com',
    measurementId: 'G-72PTBH188B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyZE0bdqUGl4whBmvls6YVtqQRVAKLAO0',
    appId: '1:400583872344:android:0ed2e2cc3ab08664d39f2d',
    messagingSenderId: '400583872344',
    projectId: 'chat-app-a3183',
    storageBucket: 'chat-app-a3183.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV50NxjjGVZZjDmBFBLncbqxPpZ60kgO0',
    appId: '1:400583872344:web:f0e0a3cd771b478ad39f2d',
    messagingSenderId: '400583872344',
    projectId: 'chat-app-a3183',
    authDomain: 'chat-app-a3183.firebaseapp.com',
    storageBucket: 'chat-app-a3183.appspot.com',
    measurementId: 'G-11DHKS6DMJ',
  );
}
